name: Benchmark

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of experimental runs'
        required: true
        default: 1
        type: number
      no_ignore:
        description: "Don't ignore implementations marked as excluded"
        required: false
        default: false
        type: boolean
      skip_cache:
        description: "Skip cache"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  set-implementations:
    runs-on: ubuntu-latest
    outputs:
      implementations: ${{ steps.implementations.outputs.implementations }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set implementations
        id: implementations
        env:
          NO_IGNORE: ${{ inputs.no_ignore && 'yes' || 'no' }}
        run: (echo -n "implementations="; ./.github/list-implementations.sh) >> $GITHUB_OUTPUT

  benchmark:
    needs: set-implementations
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/implementations/json_schemer/Gemfile
    strategy:
      matrix: ${{ fromJson(needs.set-implementations.outputs.implementations) }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Restore cached run
        uses: actions/cache/restore@v5
        id: cache-report
        with:
          path: dist/report.csv
          key: noformat-${{ matrix.impl }}-${{ hashFiles(format('implementations/{0}/**/*', matrix.impl), 'schemas/**/*', 'report.sh') }}-${{ inputs.runs || 3 }}
          lookup-only: ${{ matrix.skip_cache || github.event_name == 'schedule' || inputs.skip_cache }}

      - name: Install dts
        uses: jaxxstorm/action-install-gh-release@v3.0.0
        with:
          repo: martinohmann/dts

      - name: Run benchmarks
        if: ${{ steps.cache-report.outputs.cache-hit != 'true' || github.event_name == 'schedule' || inputs.skip_cache || matrix.skip_cache }}
        continue-on-error: ${{ true }}
        env:
          RUNS: ${{ inputs.runs || 3 }}
          IMPL: ${{ matrix.impl }}
        run: make RUNS=${RUNS} IMPLEMENTATIONS=${IMPL} dist/report.csv

      - name: Upload Report
        uses: actions/upload-artifact@v7
        with:
          name: report-${{ matrix.impl }}
          archive: false
          path: dist/report.csv
          retention-days: 1

      - name: Cache report
        uses: actions/cache/save@v5
        if: ${{ steps.cache-report.outputs.cache-hit != 'true' }}
        with:
          path: dist/report.csv
          key: ${{ steps.cache-report.outputs.cache-primary-key }}

  aggregate:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      # downloads all previously uploaded artifacts
      - name: Download Reports
        uses: actions/download-artifact@v8

      - name: Concatenate output
        run: |
          mkdir dist
          echo "implementation,version,name,cold_ns,warm_ns,parse_ns,compile_ns,memory,exit_status" > dist/report.csv
          tail -q -n +2 ./report-*/report.csv >> dist/report.csv
      - run: cat dist/report.csv
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report
          archive: false
          path: |
            dist/report.csv

  summary:
    needs: aggregate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./analytics/go.mod
      - name: Download Report
        uses: actions/download-artifact@v8
        with:
          name: report
          path: dist/
      - name: Add heading 1
        run: 
          echo "# Results Per Implementation" >> $GITHUB_STEP_SUMMARY  
      - name: Analyse Results Per Implementation
        run: 
          (cd analytics/cmd/impls && go run main.go --format=md --schemasFolder=../../../schemas ../../../dist/report.csv >> $GITHUB_STEP_SUMMARY)
      - name: Add heading 2
        run: 
          echo "# Results Per Schema" >> $GITHUB_STEP_SUMMARY  
      - name: ls
        run:
          ls -R | grep -C 3 report.csv
      - name: Analyse Results Per Schema
        run: 
          (cd analytics/cmd/result && go run main.go --format=md --schemasFolder=../../../schemas ../../../dist/report.csv >> $GITHUB_STEP_SUMMARY)
      - name: Add heading 3
        run: 
          echo "# Input Schemas" >> $GITHUB_STEP_SUMMARY
      - name: Analyse Schemas
        run:
          (cd analytics/cmd/schemas && go run main.go --format=md ../../../schemas >> $GITHUB_STEP_SUMMARY)
